[package]
name = "pinas-core"
version = "1.5.0"
edition = "2024"

[dependencies]
axum = { version = "0.8" }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "fs", "io-util", "net"] }
sqlx = { version = "0.9", features = [ "runtime-tokio", "sqlite" ] }
serde = { version = "1", features = ["derive"] }
sha2 = "0.11.0"
hex = "0.4"
argon2 = "0.6.0-rc.8"
password-hash = { version = "0.6.1", features = ["getrandom"] }
getrandom = "0.4"
tracing = "0.1"
